services:
  monerod:
    extends:
      file: ../compose-security-baseline/hardening.yml
      service: hardened-xlarge
    image: ghcr.io/enucatl/monerod:latest
    build:
      context: .
      dockerfile: src/Dockerfile
    cpu_shares: 128
    container_name: monerod
    restart: unless-stopped
    volumes:
      - /scratch/monerod:/monero
    ports:
      - 18080:18080
      - 18089:18089
    command:
      - "--block-download-max-size=33554432"
      - "--confirm-external-bind"
      - "--db-sync-mode=safe:sync:250000000bytes"
      - "--hide-my-port"
      - "--in-peers=0"
      - "--limit-rate-down=20000"
      - "--limit-rate-up=20000"
      - "--max-concurrency=1"
      - "--max-txpool-weight=67108864"
      - "--no-zmq"
      - "--out-peers=4"
      - "--p2p-ignore-ipv4"
      - "--p2p-use-ipv6"
      - "--prep-blocks-threads=1"
      - "--prune-blockchain"
      - "--rpc-max-connections=4"
      - "--rpc-max-connections-per-private-ip=4"
      - "--rpc-max-connections-per-public-ip=1"
      - "--rpc-restricted-bind-ip=0.0.0.0"
      - "--rpc-restricted-bind-ipv6-address=::"
      - "--rpc-restricted-bind-port=18089"
      - "--rpc-response-soft-limit=16777216"
      - "--rpc-use-ipv6"
      - "--sync-pruned-blocks"
    labels:
      - "checkmk_monitor=true"
    networks:
      - default
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

networks:
  default:
    enable_ipv6: true
    driver_opts:
      com.docker.network.endpoint.sysctls: '{"net.ipv6.conf.eth0.proxy_ndp": "1"}'
    ipam:
      driver: default
